# Copyright (C) 2012, Kevin Polulak <kpolulak@gmail.com>
#
# Egghead is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Egghead is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# FIXME: This file should be autogenerated by Autoconf, not hard-coded.

##
# Source configuration
##

INC_DIR = include
SRC_DIR = src
BIN_DIR = bin

##
# Install configuration
##

PREFIX = /usr/local/bin

##
# Build tools configuration
##

PROVE    = prove
CC       = gcc
CC_INC   = -I./include
CC_O_OUT = -o
CC_WARN  = -W -Wall -Wnonnull
CFLAGS   = $(CC_INC) -O2 -g -fstack-protector -std=c99

##
# USER TARGETS
##

all:
	rm -rf $(BIN_DIR)
	mkdir $(BIN_DIR)
	$(CC) $(CFLAGS) $(CC_INC) $(CC_WARN) \
	$(CC_O_OUT) $(BIN_DIR)/egghead $(SRC_DIR)/*

install:
	install $(BIN_DIR)/egghead $(PREFIX)/egghead

uninstall:
	rm -rf $(PREFIX)/egghead

clean:
	rm -rf $(SRC_DIR)/*.o
	rm -rf $(BIN_DIR)/

test:
	$(PROVE) tests/*.t
