++++++++[>+++++++++<-]>.    This
<+++++[>++++++<-]>-.        text
+++++++..                   contains
+++.                        invalid
<++++++++[>>++++<<-]>>.     brainfuck
<<++++[>------<-]>.         commands
<++++[>++++++<-]>.          and
+++.                        causes
------.                     an
--------.                   error
>+.                         message
